CREATE DATABASE customer_behaviour;

USE customer_behaviour;

SELECT * from customer;

-- Total revenue generated by male VS female customer
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount  from customer 
where discount_applied ='Yes' AND purchase_amount > (SELECT AVG(purchase_amount) from customer);


-- Which are the top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) as Average_review_rating FROM customer
GROUP BY item_purchased
ORDER BY Average_review_rating DESC
LIMIT 5;


-- Compare the average Purchase amounts between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as "Average Purchase Amount" FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Do subscribed customer spend more?
-- Compare average spend and total revenue betn subscribers and non subscribers

SELECT subscription_status, COUNT(customer_id) as "Total Customer", 
 ROUND(AVG(purchase_amount),2) as "Average Spend",
ROUND(SUM(purchase_amount),2) as "Total Revenue" from customer
GROUP BY subscription_status
ORDER BY "Total Revenue", "Average Spend" DESC;


-- Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Segment customers into New, Returning and loyal based on their total
with customer_type as (
	select 
		customer_id, previous_purchases,
		CASE
			WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'loyal'
            END AS customer_segment
	FROM customer)

SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;
            
            
-- Which are the top 3 most purchased prodcuts within each category
with item_counts AS (
	SELECT
		category, item_purchased, COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
	from customer 
    group by category , item_purchased)
    
SELECT item_rank, category, item_purchased , total_orders
from item_counts
where item_rank <= 3;

-- ARE Customers who are repeat buyers( more than 5 previous purchase) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- What is the revenue contribution of each age group
SELECT age_group, SUM(purchase_amount) as total_revenue FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


SELECT gender, subscription_status, COUNT(*) 
FROM customer
GROUP BY gender, subscription_status;

